name: Build, Test, and Deploy .NET App to Azure

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: app-cs2pickems
  AZURE_RESOURCE_GROUP: rg-cs2pickems
  BICEP_FILE: ./infrastructure/deploy.bicep
  PARAMETERS_FILE: ./infrastructure/parameters.json
  PACKAGE_PATH: ./publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore src/CS2Pickems.sln

      - name: Build solution
        run: dotnet build src/CS2Pickems/CS2Pickems.csproj --configuration Release --no-restore

      # - name: Run unit tests
       #  run: dotnet test ../../tests --configuration Release --no-build

      - name: Publish app
        run: dotnet publish src/CS2Pickems/CS2Pickems.csproj --configuration Release --output ${{ env.PACKAGE_PATH }}

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: ${{ env.PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package
          path: ${{ env.PACKAGE_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure using Bicep
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --template-file ${{ env.BICEP_FILE }} \
              --parameters @${{ env.PARAMETERS_FILE }}

      - name: Deploy app via ZIP
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
